name: Deploy to Azure VM

on:
  push:
    branches:
      - patch-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo " ${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Files to Azure VM
        run: scp -o StrictHostKeyChecking=no -v ~/.ssh/id_rsa index.html azureuser@20.116.54.11:/var/www/html/index.html
        
      - name: Restart Apache Server
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azureuser@20.116.54.11 'sudo systemctl restart apache2'

